"""
Description: One-time harness setup script. Run this after forking or cloning the repo.
             Generates CLAUDE.md and/or GEMINI.md (and ENVIRONMENT.md) from the templates
             in harness/templates/, stamped with the user's local Python path and project root.
             Also ensures these generated files are listed in .gitignore.
Source Data: harness/templates/*.template, user input.
Outputs: CLAUDE.md, GEMINI.md, ENVIRONMENT.md at the project root (all gitignored).
"""

import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
TEMPLATES = ROOT / "harness" / "templates"
GITIGNORE = ROOT / ".gitignore"

GENERATED = ["CLAUDE.md", "GEMINI.md", "ENVIRONMENT.md"]


def _read_template(name: str) -> str:
    path = TEMPLATES / name
    if not path.exists():
        print(f"  ERROR: Template not found: {path}")
        sys.exit(1)
    return path.read_text(encoding="utf-8")


def _write(name: str, content: str) -> None:
    dest = ROOT / name
    dest.write_text(content, encoding="utf-8")
    print(f"  Written: {dest}")


def _ensure_gitignore() -> None:
    existing = GITIGNORE.read_text(encoding="utf-8") if GITIGNORE.exists() else ""
    missing = [f for f in GENERATED if f not in existing]
    if missing:
        with GITIGNORE.open("a", encoding="utf-8") as fh:
            fh.write("\n# Harness — generated by setup_harness.py (machine-specific)\n")
            for name in missing:
                fh.write(f"{name}\n")
        print(f"  .gitignore updated: added {', '.join(missing)}")


def _prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"  {label}{suffix}: ").strip()
    return value if value else default


def _detect_python() -> str:
    venv = ROOT / ".venv" / "Scripts" / "python.exe"
    if venv.exists():
        return str(venv).replace("\\", "/")
    return str(Path(sys.executable)).replace("\\", "/")


def run() -> None:
    print("\n=== Fantasy Baseball Agent — Harness Setup ===\n")
    print("This script generates your local CLAUDE.md, GEMINI.md, and ENVIRONMENT.md")
    print("from the templates in harness/templates/. Run it once after forking.\n")

    # --- Agent selection ---
    print("Which AI agent(s) will you use?")
    print("  1 - Claude Code")
    print("  2 - Gemini CLI (Antigravity)")
    print("  3 - Both")
    choice = input("  Choice [3]: ").strip() or "3"
    agents = []
    if choice in ("1", "3"):
        agents.append("claude")
    if choice in ("2", "3"):
        agents.append("gemini")
    if not agents:
        print("  Invalid choice. Defaulting to both.")
        agents = ["claude", "gemini"]

    # --- Python executable ---
    detected = _detect_python()
    python_exe = _prompt("Python executable path", detected)

    # --- Project root ---
    project_root = _prompt("Project root path", str(ROOT).replace("\\", "/"))

    print()

    # --- Generate ENVIRONMENT.md ---
    env_content = (
        _read_template("ENVIRONMENT.md.template")
        .replace("{{PYTHON_EXECUTABLE}}", python_exe)
        .replace("{{PROJECT_ROOT}}", project_root)
    )
    _write("ENVIRONMENT.md", env_content)

    # --- Generate agent config files ---
    if "claude" in agents:
        _write("CLAUDE.md", _read_template("CLAUDE.md.template"))

    if "gemini" in agents:
        _write("GEMINI.md", _read_template("GEMINI.md.template"))

    # --- Update .gitignore ---
    _ensure_gitignore()

    # --- Next steps ---
    print("\nSetup complete. Your generated config files are gitignored.\n")
    print("Next step — set up credentials (ESPN cookies + LLM API key):")
    print(f"\n  {python_exe} scripts/credentials/setup_credentials.py\n")
    print("After that, run your first data collection:")
    print("\n  fba daily\n")


if __name__ == "__main__":
    run()
